### ISSUE TITLE
API result finishes with an error <Response [200]> ***ERROR*** Couldn't render template "search/search_sequence_funfams_results.tt: file error - search/search_sequence_results.tt: not found

### ISSUE THREAD

**Issue by JamesABaker** [UCL/cath-funfam-docs#3]
I am submitting a sequence to funfam API http://www.cathdb.info/search/by_funfhmmer.

```
{
  'fasta': '>Q7Z5H4 RecName: Full=Vomeronasal type-1 receptor 5; AltName: Full=G-protein coupled receptor GPCR26; Short=hGPCR26; AltName: Full=V1r-like receptor 5;\nMLKLVIIENMAEIMLFSLDLLLFSTDILCFNFPSKMIKLPGFITIQIFFYPQASFGISAN\nTILLLFHIFTFVFSHRSKSIDMIISHLSLIHILLLFTQAILVSLDFFGSQNTQDDLRYKV\nIVFLNKVMRGLSICTPCLLSVLQAIISPSIFSLAKLKHPSASHILGFFLFSWVLNMFIGV\nIFCCTLRLPPVKRGQSSVCHTALFLFAHELHPQETVFHTNDFEGCHLYRVHGPLKRLHGD\nYFIQTIRGYLSAFTQPACPRVSPVKRASQAILLLVSFVFTYWVDFTFSFSGGVTWINDSL\nLVWLQVIVANSYAAISPLMLIYADNQIFKTLQMLWFKYLSPPKLMLKFNRQCGSTKK\n',
  'queue': 'hmmscan_funvar'
} {
  'accept': 'application/json'
}
```

The url, http://www.cathdb.info/search/by_funfhmmer/check/ea8bf2498272b0a40c82ca22d43230c7, yields `<Response [200]>` which implies a result is present.

```
{
  'success': 1,
  'data': {
    'date_completed': '2020-01-23T13:52:26',
    'status': 'done',
    'worker_hostname': 'mothra.biochem.ucl.ac.uk',
    'id': 'ea8bf2498272b0a40c82ca22d43230c7',
    'date_started': '2020-01-23T13:52:22'
  },
  'message': 'done'
}
```

However, the results page only contains an error.
http://www.cathdb.info/search/by_funfhmmer/results/ea8bf2498272b0a40c82ca22d43230c7

```
Content-Type text/html had a problem with your request.
***ERROR***
Couldn't render template "search/search_sequence_funfams_results.tt: file error - search/search_sequence_results.tt: not found"
```

The url does not display a result via a browser

http://www.cathdb.info/search/by_sequence?task_id=ea8bf2498272b0a40c82ca22d43230c7

![Screenshot 2020-01-23 at 14 11 43](https://user-images.githubusercontent.com/6866798/72991678-50797480-3dea-11ea-9830-e73c707d6eae.png)

**Comment by sillitoe** [comment]
Thanks for raising the issue as a ticket.

This endpoint is meant to be accessed via API rather than a web page - you can get the json by adding `accept: application/json` to the header.

```
curl -H 'accept:application/json' http://www.cathdb.info/search/by_funfhmmer/results/ea8bf2498272b0a40c82ca22d43230c7
```
which outputs:

```
{"query_fasta":">P31644 RecName FullGam...
```

The error you see when trying to look at this endpoint in a browser is not helpful though. I'll fix that to display something more sensible.

**Comment by JamesABaker** [comment]
I see. I was downloading the page contents rather than fetching the API request. D'OH!

Yes, the actual response looks as expected.
